#source '~/.cocoapods/repos/local-specs'
#source 'jose@localhost:.cocoapods/repos/local-specs'
#source 'jose@localhost:.cocoapods/repos/master'
use_frameworks!
target 'NGApi_Tests' do
    pod 'NGAEssentials', path: '~/swift/pods/NGAEssentials'
  pod 'NGApi', :path => '../'
  
  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
end
